  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      # هذا هو الإصدار الذي ثبت أنه يعمل، تم تعديله من 3.10.0
      flutter-version: '3.19.6' 
      channel: 'stable'

  - name: Enable web
    working-directory: app
    run: flutter config --enable-web

  - name: Install dependencies
    working-directory: app
    run: flutter pub get

  # خطوة تصحيح الخطأ "Could not find an option named release"
  # تم إضافة "--web-renderer html" لحل مشكلة البناء في البيئة التلقائية
  - name: Build web
    working-directory: app
    run: flutter build web --web-renderer html --release

  - name: Build APK (release)
    working-directory: app
    run: flutter build apk --release

  - name: Upload web artifact
    uses: actions/upload-artifact@v4
    with:
      name: adlukk-web
      path: app/build/web

  - name: Upload APK artifact
    uses: actions/upload-artifact@v4
    with:
      name: adlukk-apk
      path: app/build/app/outputs/flutter-apk/app-release.apk
